services:
  api:
    build: .
    container_name: fraud-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CCFD_HF_REPO=matheuscosta22/credit-card-fraud
      - CCFD_HF_TOKEN=
    command: poetry run uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 600
